### ISSUE TITLE
Nested inputobject in mutation input cannot be optional

### ISSUE THREAD

**Issue by kristofdepypere** [andimarek/graphql-java#72]
Suppose you do a relay-like mutation, with input object AddFriend as input object type. This input object type contains another List of nested input object types which is optional. The schema is more or less like follows:

```
{
          "kind": "INPUT_OBJECT",
          "name": "AddFriend",
          "description": null,
          "fields": null,
          "inputFields": [
            {
              "name": "clientMutationId",
              "description": null,
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "defaultValue": null
            },
            {
              "name": "sharingRules",
              "description": null,
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "INPUT_OBJECT",
                  "name": "AddSharingRule",
                  "ofType": null
                }
              },
              "defaultValue": null
            }
          ],
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": null
        }
```

If you send a mutation without any Sharing rule, you get a nullpointer with the followinng stacktrace:

```
java.lang.NullPointerException
	at graphql.execution.ValuesResolver.coerceValueForInputObjectField(ValuesResolver.java:84)
	at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:74)
	at graphql.execution.ValuesResolver.coerceValueForList(ValuesResolver.java:107)
	at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:72)
	at graphql.execution.ValuesResolver.coerceValueForInputObjectField(ValuesResolver.java:84)
	at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:74)
	at graphql.execution.ValuesResolver.getVariableValue(ValuesResolver.java:59)
	at graphql.execution.ValuesResolver.getVariableValues(ValuesResolver.java:16)
	at graphql.execution.ExecutionContextBuilder.build(ExecutionContextBuilder.java:55)
	at graphql.execution.Execution.execute(Execution.java:32)
	at graphql.GraphQL.execute(GraphQL.java:78)
	at graphql.GraphQL.execute(GraphQL.java:55)
```

**Comment by andimarek** [comment]
Pleas try again with latest master ... this should be fixed now.

**Comment by lelong71** [comment]
I ran into the same issue and the latest pull doesn't fix. This PR https://github.com/andimarek/graphql-java/pull/80 fix both - NPE and required field not validated.

**Comment by andimarek** [comment]
@lelong71 @kristofdepypere  Please try again with the latest build.

**Comment by lelong71** [comment]
I confirm that this is fixed. Thanks
